#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: dunkebiao
 * Date: 2019-04-27
 * Time: 11:15
 */


error_reporting(E_ERROR);

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

foreach (array(__DIR__ . '/../../../bootstrap/app.php', __DIR__ . '/../../bootstrap/app.php', __DIR__ . '/bootstrap/app.php') as $file) {
    if (file_exists($file)) {
        $app = require_once $file;
        break;
    }
}

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$config = [
    'worker_num' => 4,
    'log_file' => 'http.log',
    'upload_tmp_dir' => '/tmp/',
    'http_parse_post' => true,
    'document_root' => __DIR__ . '../public',
    'enable_static_handler' => true,
    'http_compression' => true,
];

$server = new \Swoole\Laravel\HttpServer(
    '127.0.0.1',
    '8080',
    SWOOLE_PROCESS,
    SWOOLE_SOCK_TCP
);
$server->set($config);
$server->setLaravel($kernel);
$server->start();